"""empty message

Revision ID: 873b9d3447b4
Revises: 337195d88dcd
Create Date: 2017-07-13 20:40:26.788471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873b9d3447b4'
down_revision = '337195d88dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_todos_url_token'), 'todos', ['url_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_url_token'), table_name='todos')
    # ### end Alembic commands ###
